runtime: nodejs
env: flex
entrypoint: npm start
env_variables:
  ATLAS_URI: "mongodb+srv://user:5610Final@traveladvisor.dg74epg.mongodb.net/?retryWrites=true&w=majority"
runtime_config:
  operating_system: ubuntu22
# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10